### ISSUE TITLE
Archive in LotroInterface has weird file names

### ISSUE THREAD

**Issue by Thaodan** [LilianHiault/ChatNotif#13]
Something is wrong with the zip archive you upload on lotro interface. The archive uses backslashes instead of slashes.
Using backslashes in zip archives is wrong according to [ZIP File Format Specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) (version: 6.3.5 when I'm writing this, revised November 20, 2018) states:

>    4.4.17.1 The name of the file, with optional relative path. The path stored MUST NOT contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes / as opposed to backwards slashes \ for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

Are you using powershell to create the archive? If I read correctly there a bug in older versions.

Source for the likely reason of the issue:
https://superuser.com/a/1410005/957373

**Comment by EsyArda** [comment]
Yes I use Powershell version 5.1.
I tested the LotroInterface zip on my Linux laptop and even though there is a warning about backslahses, it doesn't affect the result. Everything seems to work on my machine. Are there any files broken on yours ?
![Screenshot at 2023-07-01 15-33-12](https://github.com/EsyArda/ChatNotif/assets/34962237/b6a76983-4912-499f-bd1e-780de6b482f1)

**Comment by Thaodan** [comment]
For my unzip -l at least showed the archive with backslashes, Ark did so
too.
I didn't extract the archive using but used bsdtar where it did work fine.

**Comment by EsyArda** [comment]
If everything works fine, I probably won't fix it sorry 🙁
